using Assigment2.Models;
using Assigment2.Models.interfaces;
using Assigment2.Models.Repositroy;
using Assigment2.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Assigment2.Controllers
{
    public class DeparmentController : Controller
    {
        //we can  inject in constructor ,method,property but MVC prefer to use Only constructor
        private readonly IDepartmentRepository _DepartmentRepoistory;//= new IDepartmentRepoistory();
        ITraineeRepository _TraineeRepoistory; //= new ITraineeRepoistory();
        public DeparmentController(IDepartmentRepository DepartmentRepoistory, ITraineeRepository TraineeRepoistory)
        {
            _DepartmentRepoistory = DepartmentRepoistory;
            _TraineeRepoistory = TraineeRepoistory;
        }
        [HttpGet]
        public IActionResult Index(int pg = 1)
        {
            const int pageSize = 8;
            var query = _DepartmentRepoistory.GetAll2(); // Returns IQueryable<Course>

            int recsCount = query.Count(); // Executes SQL COUNT()
            int totalPages = (int)Math.Ceiling(recsCount / (double)pageSize);

            // Ensure pg is within valid range
            pg = Math.Clamp(pg, 1, totalPages > 0 ? totalPages : 1);

            // Apply pagination at the database level
            var data = query.Skip((pg - 1) * pageSize).Take(pageSize).ToList();

            // Ensure totalPages is at least 1 in PagedResult
            var pager = new PagedResult(recsCount, pg, pageSize);
            ViewBag.Pager = pager;

            return View(data);
        }



        [HttpPost]
        public IActionResult Delete(int id)
        {
            Department department = _DepartmentRepoistory.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
            _DepartmentRepoistory.Delete(department.DepartmentId);
            return Ok();
        }

        public IActionResult AddNew()

        {

            return View(new Department());
        }

     //   [ValidateAntiForgeryToken]// to prevent CSRF attack 
                                  // only the form that generated by the server will be accepted
                                  // otherwise will not exucuted (call internal)only on post method
    
        [HttpGet]       
        public IActionResult Edit(int id)
        {
            var department = _DepartmentRepoistory.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
            return View("AddNew", department); // Return the same view with the existing department data
        }
        // only on tag helper and html helper
        public async Task<IActionResult> SaveEdit(Department UpdatedDepartment)
        {
            // Validate Model
            if (!ModelState.IsValid)
            {
                return View("AddNew", UpdatedDepartment);
            }

            if (UpdatedDepartment.DepartmentId == 0) // Adding a new Department
            {
                var newDepartment = new Department
                {
                    Name = UpdatedDepartment.Name,
                    Manager = UpdatedDepartment.Manager,
                };
                _DepartmentRepoistory.Add(newDepartment);
            }
            else // Updating an existing Department
            {
                var existingDepartment = _DepartmentRepoistory.GetById(UpdatedDepartment.DepartmentId);
                if (existingDepartment == null)
                {
                    return NotFound(); // Return 404 if department is not found
                }

                // ✅ Correctly updating existing record
                existingDepartment.Name = UpdatedDepartment.Name;
                existingDepartment.Manager = UpdatedDepartment.Manager;

                _DepartmentRepoistory.Update(existingDepartment.DepartmentId, existingDepartment);
            }

            return RedirectToAction("Index");
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken] // للحماية من هجمات CSRF
        //                           //public IActionResult SaveNew(Department department)
        //{
        //    if (!ModelState.IsValid) // التحقق من صحة النموذج
        //    {
        //        return View("New", department); // إعادة عرض النموذج مع الأخطاء
        //    }

        //    try
        //    {
        //        using (var context = new AppDbContext())
        //        {
        //            context.Departments.Add(department);
        //            context.SaveChanges();
        //        }

        //        return RedirectToAction("Index"); // إعادة التوجيه بعد الحفظ بنجاح
        //    }
        //    catch (Exception ex)
        //    {
        //        // إذا حدث خطأ، أضفه إلى ModelState لإظهاره في الواجهة
        //        ModelState.AddModelError(string.Empty, "حدث خطأ أثناء حفظ البيانات. يرجى المحاولة مرة أخرى.");

        //        // إضافة الخطأ الفعلي في ملخص الأخطاء
        //        ModelState.AddModelError(string.Empty, ex.Message);

        //        // إعادة عرض الصفحة مع عرض الأخطاء
        //        return View("New", department);
        //    }
        //}

    }
}

